// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// internalBookborrowinformationDao is internal type for wrapping internal DAO implements.
type internalBookborrowinformationDao = *internal.BookborrowinformationDao

// bookborrowinformationDao is the data access object for table bookborrowinformation.
// You can define custom methods on it to extend its functionality as you wish.
type bookborrowinformationDao struct {
	internalBookborrowinformationDao
}

var (
	// Bookborrowinformation is globally public accessible object for table bookborrowinformation operations.
	Bookborrowinformation = bookborrowinformationDao{
		internal.NewBookborrowinformationDao(),
	}
)

// Fill with you ideas below.
