// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// internalBooktypeDao is internal type for wrapping internal DAO implements.
type internalBooktypeDao = *internal.BooktypeDao

// booktypeDao is the data access object for table booktype.
// You can define custom methods on it to extend its functionality as you wish.
type booktypeDao struct {
	internalBooktypeDao
}

var (
	// Booktype is globally public accessible object for table booktype operations.
	Booktype = booktypeDao{
		internal.NewBooktypeDao(),
	}
)

// Fill with you ideas below.
