// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// internalBookinformationDao is internal type for wrapping internal DAO implements.
type internalBookinformationDao = *internal.BookinformationDao

// bookinformationDao is the data access object for table bookinformation.
// You can define custom methods on it to extend its functionality as you wish.
type bookinformationDao struct {
	internalBookinformationDao
}

var (
	// Bookinformation is globally public accessible object for table bookinformation operations.
	Bookinformation = bookinformationDao{
		internal.NewBookinformationDao(),
	}
)

// Fill with you ideas below.
