// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// internalGfUserDao is internal type for wrapping internal DAO implements.
type internalGfUserDao = *internal.GfUserDao

// gfUserDao is the data access object for table gf_user.
// You can define custom methods on it to extend its functionality as you wish.
type gfUserDao struct {
	internalGfUserDao
}

var (
	// GfUser is globally public accessible object for table gf_user operations.
	GfUser = gfUserDao{
		internal.NewGfUserDao(),
	}
)

// Fill with you ideas below.
