// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// internalLibraryDao is internal type for wrapping internal DAO implements.
type internalLibraryDao = *internal.LibraryDao

// libraryDao is the data access object for table library.
// You can define custom methods on it to extend its functionality as you wish.
type libraryDao struct {
	internalLibraryDao
}

var (
	// Library is globally public accessible object for table library operations.
	Library = libraryDao{
		internal.NewLibraryDao(),
	}
)

// Fill with you ideas below.
